export default {
  html: [
    {
      id: '1',
      text: 'Co znamená zkratka HTML?',
      source: [
        { text: 'Home Tool Markup Language' },
        { text: 'Hyperlinks and Text Markup Language' },
        { text: 'Hyper Text Markup Language' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '2',
      text: 'Který z těchto tagů je uzavírací?',
      source: [
        { text: '<b>' },
        { text: '<b/>' },
        { text: '</b>' },
        { text: '</b/>' },
      ],
      ok: ' ',
      link: '',
    },
    {
      id: '3',
      text: 'Vyberte správný HTML tag pro největší nadpis.',
      source: [
        { text: '<big>' },
        { text: '<h6>' },
        { text: '<head>' },
        { text: '<h1>' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '4',
      text: 'Vyberte správný HTML tag pro odstavec.',
      source: [{ text: '<b>' }, { text: '<p>' }, { text: '<o>' }],
      ok: '',
      link: '',
    },
    {
      id: '5',
      text: 'Vyberte správný HTML tag pro písmo psané kurzívou.',
      source: [
        { text: '<i>' },
        { text: '<ii>' },
        { text: '<italy>' },
        { text: '<italic>' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '6',
      text: 'Která z těchto možností má správný tvar pro HTML odkaz?',
      source: [
        { text: 'a>http://www.klikzone.cz</a>' },
        { text: '<a name="http://www.adresa.cz">adresa.cz</a>' },
        { text: '<a href="http://www.adresa.cz">adresa.cz</a>' },
        { text: '<a url="http://www.adresa.cz">adresa.cz</a>' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '7',
      text: 'Která z těchto možností má správný tvar pro e-mailový odkaz?',
      source: [
        { text: '<a href="mailto:postmaster@email.cz">' },
        { text: '<mail>postmaster@email.cz</mail>' },
        { text: '<a href="postmaster@email.cz">' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '8',
      text: 'Pomocí kterého HTML tagu vytvoříte očíslovaný seznam?',
      source: [
        { text: '<num>' },
        { text: '<ol>' },
        { text: '<ul>' },
        { text: '<list>' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '9',
      text: 'Která z těchto možností má správný tvar pro vložení obrázku?',
      source: [
        { text: '<image src="image.gif">' },
        { text: '<img src="image.gif">' },
        { text: '<img>image.gif</img>' },
        { text: '<img href="image.gif>' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '10',
      text: 'Jak vytvoříte vodorovnou čáru?',
      source: [{ text: '<hr>' }, { text: '</hr>' }, { text: '<br>' }],
      ok: '',
      link: '',
    },
    {
      id: '11',
      text: 'Jak se zapisují pomocné HTML komentáře?',
      source: [
        { text: '<-- OBSAH ZAČÍNÁ ZDE -->' },
        { text: '<!-- OBSAH ZAČÍNÁ ZDE --!>' },
        { text: '<-- OBSAH ZAČÍNÁ ZDE --!>' },
        { text: '<!-- OBSAH ZAČÍNÁ ZDE -->' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '12',
      text: 'Kam se v HTML dokumentu vkládají metadata?',
      source: [
        { text: 'do sekce <body>' },
        { text: 'do menu' },
        { text: 'do sekce <head>' },
        { text: 'nikam, metadata se vkládají do externího CSS souboru' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '13',
      text: 'Jak vytvoříte textové pole?',
      source: [
        { text: '<input type="text"/>' },
        { text: '<input type="textfield">' },
        { text: '<textfield>' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '14',
      text: 'Vyberte možnost pro kterou platí, že všechny tagy patří do tabulky.',
      source: [
        { text: '<html><head><body>' },
        { text: '<table><tt><tr>' },
        { text: '<table><td><tr>' },
        { text: '<table><head><tfoot>' },
      ],
      ok: '',
      link: '',
    },
    {
      id: '15',
      text: 'Je možné vložit do obrázku odkaz?',
      source: [{ text: 'ano' }, { text: 'ne' }],
      ok: '',
      link: '',
    },
    {
      id: '16',
      text: 'Tag <font>?',
      source: [
        { text: 'je nový a perspektivní' },
        { text: 'má mnohem větší možnosti, než CSS' },
        { text: 'je zastaralý, na formátování textu se používá CSS' },
        { text: 'se používá pouze v XHTML' },
      ],
      ok: '',
      link: 'https://www.w3schools.com/tags/tag_font.asp',
    },
    {
      id: '17',
      text: 'Počet úrovní nadpisů v HTML je?',
      source: [{ text: '3' }, { text: '4' }, { text: '5' }, { text: '6' }],
      ok: '',
      link: 'https://www.w3schools.com/html/html_headings.asp',
    },
    {
      id: '18',
      text: 'Atribut lang v tomto kódu <p lang="en-GB">Welcome to our wonderful website.</p>',
      source: [
        { text: 'Určuje jazyk webových stránek - v tomto případě angličtinu.' },
        {
          text: 'Určuje jazyk a místní podobu jazyka použitou pro webové stránky - v tomto případě britskou angličtinu.',
        },
        {
          text: 'Určuje jazyk a místní podobu jazyka použitou pro odstavce - v tomto případě britskou angličtinu. Určuje jazyk odstavce - v tomto případě angličtinu.',
        },
      ],
      ok: '',
      link: 'https://stackoverflow.com/questions/11318961/what-is-the-difference-between-html-lang-en-and-html-lang-en-us',
    },
    {
      id: '19',
      text: 'Stejný identifikátor se může vyskytnout maximálně:',
      source: [
        { text: '1× v odlíle (sekci)' },
        { text: '1× v na celém website' },
        { text: 'prakticky neomezeně' },
        { text: '1× na stránce' },
      ],
      ok: '',
      link: 'http://htmlguru.cz/css-selektor-id.html',
    },
    {
      id: '20',
      text: 'Stejná třída se může vyskytnout maximálně:',
      source: [
        { text: '1× v odlíle (sekci)' },
        { text: '1× v na celém website' },
        { text: 'prakticky neomezeně' },
        { text: '1× na stránce' },
      ],
      ok: '',
      link: 'http://htmlguru.cz/css-selektor-trida.html',
    },
  ],
};
