export default {
  html: [
    {
      id: '1',
      text: 'Co znamená zkratka HTML?',
      source: [
        { text: 'Home Tool Markup Language' },
        { text: 'Hyperlinks and Text Markup Language' },
        { text: 'Hyper Text Markup Language' },
      ],
      ok: 2,
      link: 'https://cs.wikipedia.org/wiki/Hypertext_Markup_Language',
    },
    {
      id: '2',
      text: 'Který z těchto tagů je uzavírací?',
      source: [
        { text: '<b>' },
        { text: '<b/>' },
        { text: '</b>' },
        { text: '</b/>' },
      ],
      ok: 2,
      link: 'https://cs.khanacademy.org/computing/computer-programming/html-css/intro-to-html/a/quick-tip-html-tags',
    },
    {
      id: '3',
      text: 'Vyberte správný HTML tag pro největší nadpis.',
      source: [
        { text: '<big>' },
        { text: '<h6>' },
        { text: '<head>' },
        { text: '<h1>' },
      ],
      ok: 3,
      link: 'https://jecas.cz/nadpisy',
    },
    {
      id: '4',
      text: 'Vyberte správný HTML tag pro odstavec.',
      source: [{ text: '<b>' }, { text: '<p>' }, { text: '<o>' }],
      ok: 1,
      link: 'https://www.jakpsatweb.cz/html/bloky.html',
    },
    {
      id: '5',
      text: 'Vyberte správný HTML tag pro písmo psané kurzívou.',
      source: [
        { text: '<i>' },
        { text: '<ii>' },
        { text: '<italy>' },
        { text: '<italic>' },
      ],
      ok: 0,
      link: 'https://www.jakpsatweb.cz/css/font-style.html',
    },
    {
      id: '6',
      text: 'Která z těchto možností má správný tvar pro HTML odkaz?',
      source: [
        { text: 'a>http://www.adresa.cz</a>' },
        { text: '<a name="http://www.adresa.cz">adresa.cz</a>' },
        { text: '<a href="http://www.adresa.cz">adresa.cz</a>' },
        { text: '<a url="http://www.adresa.cz">adresa.cz</a>' },
      ],
      ok: 2,
      link: 'https://www.jakdelatweby.cz/html/odkazy.php',
    },
    {
      id: '7',
      text: 'Která z těchto možností má správný tvar pro e-mailový odkaz?',
      source: [
        { text: '<a href="mailto:postmaster@email.cz">' },
        { text: '<mail>postmaster@email.cz</mail>' },
        { text: '<a href="postmaster@email.cz">' },
      ],
      ok: 0,
      link: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a',
    },
    {
      id: '8',
      text: 'Pomocí kterého HTML tagu vytvoříte očíslovaný seznam?',
      source: [
        { text: '<num>' },
        { text: '<ol>' },
        { text: '<ul>' },
        { text: '<list>' },
      ],
      ok: 1,
      link: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol',
    },
    {
      id: '9',
      text: 'Která z těchto možností má správný tvar pro vložení obrázku?',
      source: [
        { text: '<image src="image.gif">' },
        { text: '<img src="image.gif">' },
        { text: '<img>image.gif</img>' },
        { text: '<img href="image.gif>' },
      ],
      ok: 1,
      link: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img',
    },
    {
      id: '10',
      text: 'Jak vytvoříte vodorovnou čáru?',
      source: [{ text: '<hr>' }, { text: '</hr>' }, { text: '<br>' }],
      ok: 0,
      link: 'https://www.w3schools.com/tags/tag_hr.asp',
    },
    {
      id: '11',
      text: 'Jak se zapisují pomocné HTML komentáře?',
      source: [
        { text: '<-- OBSAH ZAČÍNÁ ZDE -->' },
        { text: '<!-- OBSAH ZAČÍNÁ ZDE --!>' },
        { text: '<-- OBSAH ZAČÍNÁ ZDE --!>' },
        { text: '<!-- OBSAH ZAČÍNÁ ZDE -->' },
      ],
      ok: 3,
      link: 'http://htmlguru.cz/zaklady-komentare.html',
    },
    {
      id: '12',
      text: 'Kam se v HTML dokumentu vkládají metadata?',
      source: [
        { text: 'do sekce <body>' },
        { text: 'do menu' },
        { text: 'do sekce <head>' },
        { text: 'nikam, metadata se vkládají do externího CSS souboru' },
      ],
      ok: 2,
      link: 'https://www.jakpsatweb.cz/meta-tagy.html',
    },
    {
      id: '13',
      text: 'Jak vytvoříte textové pole?',
      source: [
        { text: '<input type="text"/>' },
        { text: '<input type="textfield">' },
        { text: '<textfield>' },
      ],
      ok: 0,
      link: 'https://www.jakpsatweb.cz/html/formulare.html',
    },
    {
      id: '14',
      text: 'Vyberte možnost pro kterou platí, že všechny tagy patří do tabulky.',
      source: [
        { text: '<html><head><body>' },
        { text: '<table><tt><tr>' },
        { text: '<table><td><tr>' },
        { text: '<table><head><tfoot>' },
      ],
      ok: 2,
      link: 'https://www.jakpsatweb.cz/html/tabulky.html#table',
    },
    {
      id: '15',
      text: 'Je možné vložit do obrázku odkaz?',
      source: [{ text: 'ano' }, { text: 'ne' }],
      ok: 0,
      link: 'http://polopate.jakpsatweb.cz/index.php?page=odkazy2',
    },
    {
      id: '16',
      text: 'Tag <font>?',
      source: [
        { text: 'je nový a perspektivní' },
        { text: 'má mnohem větší možnosti, než CSS' },
        { text: 'je zastaralý, na formátování textu se používá CSS' },
        { text: 'se používá pouze v XHTML' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/tags/tag_font.asp',
    },
    {
      id: '17',
      text: 'Počet úrovní nadpisů v HTML je?',
      source: [{ text: '3' }, { text: '4' }, { text: '5' }, { text: '6' }],
      ok: 3,
      link: 'https://www.w3schools.com/html/html_headings.asp',
    },
    {
      id: '18',
      text: 'Atribut lang v tomto kódu <p lang="en-GB">Welcome to our wonderful website.</p>',
      source: [
        { text: 'Určuje jazyk webových stránek - v tomto případě angličtinu.' },
        {
          text: 'Určuje jazyk a místní podobu jazyka použitou pro webové stránky - v tomto případě britskou angličtinu.',
        },
        {
          text: 'Určuje jazyk a místní podobu jazyka použitou pro odstavce - v tomto případě britskou angličtinu. Určuje jazyk odstavce - v tomto případě angličtinu.',
        },
      ],
      ok: 2,
      link: 'https://stackoverflow.com/questions/11318961/what-is-the-difference-between-html-lang-en-and-html-lang-en-us',
    },
    {
      id: '19',
      text: 'Stejný identifikátor se může vyskytnout maximálně:',
      source: [
        { text: '1× v odlíle (sekci)' },
        { text: '1× v na celém website' },
        { text: 'prakticky neomezeně' },
        { text: '1× na stránce' },
      ],
      ok: 3,
      link: 'http://htmlguru.cz/css-selektor-id.html',
    },
    {
      id: '20',
      text: 'Stejná třída se může vyskytnout maximálně:',
      source: [
        { text: '1× v odlíle (sekci)' },
        { text: '1× v na celém website' },
        { text: 'prakticky neomezeně' },
        { text: '1× na stránce' },
      ],
      ok: 2,
      link: 'http://htmlguru.cz/css-selektor-trida.html',
    },
    {
      id: '21',
      text: 'Kdy se používá značka <link>?',
      source: [
        {
          text: 'Při propojování souborů se styly, JavaScriptu a ikon pro mobilní aplikace',
        },
        { text: 'Při propojování souborů se styly, faviconů a assets' },
        { text: 'Při propojování souborů se styly a faviconů' },
        {
          text: 'Při propojování souborů se styly, externích adres URL a faviconů',
        },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/tags/tag_link.asp',
    },
    {
      id: '22',
      text: 'K jakým značkám se pojí atribut value?',
      source: [
        { text: '<button><input><form>' },
        { text: '<input><label><meter>' },
        { text: '<input><option><textarea>' },
        { text: '<li><input><option>' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/tags/att_input_value.asp',
    },
    {
      id: '23',
      text: 'K jakým značkám se pojí atribut value?',
      source: [
        { text: '<button><input><form>' },
        { text: '<input><label><meter>' },
        { text: '<input><option><textarea>' },
        { text: '<li><input><option>' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/tags/att_input_value.asp',
    },
    {
      id: '24',
      text: 'Doplňte do mezer <address ______ _____> <span itemprop="streetAddress">6410 Via Real</span><br /> <span itemprop="addressLocality">Carpinteria</span>, <span itemprop="addressRegion">CA</span> <span itemprop="addressCode">93013</span> </address>',
      source: [
        { text: 'itemscope itemtype="http://schema.org/PostalAddress"' },
        { text: 'itemsref="http://schema.org/PostalAddress" itemid="address"' },
        { text: 'itemscope itemref="http://schema.org/PostalAddress"' },
        { text: 'itemid="address" itemtype="http://schema.org/PostalAddress"' },
      ],
      ok: 0,
      link: 'https://www.tutorialspoint.com/html5/html5_microdata.htm',
    },
    {
      id: '25',
      text: 'Element aside se používá:',
      source: [
        { text: 'pro cokoli, co nepatří k hlavnímu tématu daného bloku' },
        {
          text: 'pro cokoli, co chcete posunout na stranu ať už je to sidebar nebo obrázekobtékaný textem',
        },
        { text: 'pro cokoli v závorkách' },
        { text: 'pro cokoli v sidebaru' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/tags/tag_aside.asp',
    },
    {
      id: '26',
      text: 'Se kterými značkami se pojí prvek source?',
      source: [
        { text: '<svg>, <picture>, <audio>, and <video>' },
        { text: '<picture>, <audio>, and <video>' },
        {
          text: 'Protože je zaměnitelný s atributem src <source>, takže pro elementy, které používají src, můžeme použít <source>',
        },
        { text: '<audio> and <video>' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/tags/tag_source.asp',
    },
    {
      id: '27',
      text: 'Který atribut se nepoužívá pro <input>?',
      source: [
        { text: '<input type = "color">' },
        { text: '<input type = "tel">' },
        { text: '<input type = "week">' },
        { text: '<input type = "num">' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/tags/tag_input.asp',
    },
    {
      id: '28',
      text: 'Který HTML kód po kliknutí telefonuje na uvedené číslo?',
      source: [
        { text: '<a href="tel: 802-555-1212">Call me</a>' },
        { text: '<a href="phone">802-555-1212</a>' },
        { text: '<a href="tel">802-555-1212</a>' },
        { text: '<a href="phone: 802-555-1212">Call me</a>' },
      ],
      ok: 0,
      link: 'https://developers.google.com/web/fundamentals/native-hardware/click-to-call',
    },
    {
      id: '29',
      text: 'Defer v kódu <script defer src = "myscript.js"> </script>?',
      source: [
        { text: 'Stahuje skript ze serveru.' },
        { text: 'Spouští skript po dokončení HTML analýzy („parsování“)' },
        { text: 'Spouští skript jakmile je to možné' },
        { text: 'Při spuštění skriptu pozastavuje analýzu HTML („parsování“)' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/tags/att_script_defer.asp',
    },
    {
      id: '30',
      text: 'Co je kořenový prvek v HTML? ',
      source: [
        { text: '<!DOCTYPE html>' },
        { text: '<html>' },
        { text: '<root>' },
        { text: '<body>' },
      ],
      ok: 1,
      link: 'https://www.w3.org/TR/2010/WD-html-markup-20100624/html.html',
    },
    {
      id: '31',
      text: 'Jáka sémantická značka se v HTML používá pro citování?',
      source: [
        { text: '<q>' },
        { text: '<quote>' },
        { text: '<blockquote>' },
        { text: '<notation>' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/html/html_quotation_elements.asp',
    },
    {
      id: '32',
      text: 'Jak vypadají komentáře v HTML?',
      source: [
        { text: '//komentář' },
        { text: '/* komentář */' },
        { text: '<! komentář ->' },
        { text: '<!-- komentář -->' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/html/html_comments.asp',
    },
    {
      id: '33',
      text: 'Jakým způsobem připojujeme soubory se styly (style.css) do HTML dokumentu?',
      source: [
        { text: '<style link="style.css">' },
        { text: '<link rel="stylesheet" href="style.css">' },
        { text: '<style src="style.css"></style>' },
        { text: '<link style="style.css">' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/tags/att_link_rel.asp',
    },
    {
      id: '34',
      text: 'Které formáty obrázků zobrazuje většina webových prohlížečů?',
      source: [
        { text: 'JPG, GIF, TIF' },
        { text: 'JPG, TIF, BMP' },
        { text: 'TIF, BMP, GIF' },
        { text: 'PNG, GIF, JPG' },
      ],
      ok: 3,
      link: 'https://www.vzhurudolu.cz/prirucka/obrazky-formaty',
    },
    {
      id: '35',
      text: 'Jaký je správný kód odkazu, který po kliknutí odešle e-mail na e-mail@example.com s předmětem „Dobrý den“?',
      source: [
        {
          text: '<a href="mailto:email@example.com&subject=Hello">Click me</a>',
        },
        { text: '<a href="mailto:email@example.com">Hello</a>' },
        {
          text: '<a href="mailto:email@example.com?subject=Hello">Click me</a>',
        },
        {
          text: '<a href="mailto:email@example.com?&subject=Hello">Click me</a>',
        },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/tags/tag_address.asp',
    },
    {
      id: '36',
      text: 'Jakým atributem aktivujeme určitý prvek na stránce stisknutím určité klávesy?',
      source: [
        { text: 'accesskey' },
        { text: 'shortcut' },
        { text: 'keyboard' },
        { text: 'access' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/tags/att_global_accesskey.asp',
    },
    {
      id: '37',
      text: 'Jak sémanticky nejlépe označit, že text odkazuje na vstup z klávesnice?',
      source: [
        { text: '<p>Zmáčkněte <tt>Enter</tt> a pokračujte.</p>' },
        { text: '<p>Zmáčkněte <kbd>Enter</kbd> a pokračujte.</p>' },
        { text: '<p>Zmáčkněte <samp>Enter</samp> a pokračujte.</p>' },
        { text: '<p>K pokračování zmáčkněte Enter.</p>' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/tags/tag_kbd.asp',
    },
    {
      id: '38',
      text: 'Doplňte do mezery <link href="phone.css" rel="stylesheet" _____="print" />:',
      source: [
        { text: 'title' },
        { text: 'type' },
        { text: 'device' },
        { text: 'media' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/tags/att_link_media.asp',
    },
    {
      id: '39',
      text: 'Chceme-li, aby se odkaz otevřel v novém okně, použijeme atribut:',
      source: [
        { text: '_blank' },
        { text: '_self' },
        { text: '_new' },
        { text: '_parent' },
      ],
      ok: 0,
      link: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rp',
    },
    {
      id: '40',
      text: 'Co má na starosti tento kód <audio controls src="sound.mp3" type="audio/mpeg">When does this text display?</audio>?',
      source: [
        {
          text: 'Text se zobrazí nad ovládacími prvky zvuku, pokud ho pomocí CSS neumístíme jinam.',
        },
        { text: 'Text se zobrazí pod ovládacími prvky zvuku.' },
        { text: 'Text se zobrazí, pokud prohlížeč nedokáže přehrát zvuk.' },
        { text: 'Text se nikdy nezobrazí.' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/html/html5_audio.asp',
    },

    {
      id: '41',
      text: 'Které tři značky byly v HTML4 zastaralé, ale začal se zmovu používat v HTML5?',
      source: [
        { text: '<rb> <rp> <rt>nk' },
        { text: '<acronym> <code> <wbr>' },
        { text: '<hgroup> <q> <wbr>' },
        { text: '<b> <i> <u>' },
      ],
      ok: 0,
      link: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element/rp',
    },
    {
      id: '42',
      text: 'Doplňte do mezery <a href="https://es.yahoo.com/" hreflang="____" target="_blank">Visita Yahoo</a>:',
      source: [
        { text: 'es' },
        { text: 'es-spanish' },
        { text: 'es-es' },
        { text: 'spanish' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/tags/ref_language_codes.asp',
    },
    {
      id: '43',
      text: 'Doplňte do mezery <form method="post" action="mailto:info@linkedin.com" ____="text/plain">',
      source: [
        { text: 'enctype' },
        { text: 'media' },
        { text: 'type' },
        { text: 'rel' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/tags/ref_language_codes.asp',
    },
    // {
    //   id: '44',
    //   text: ' Doplňte do mezery v kódu: <section itemscope itemtype="http://schema.org/Restaurant">
    //   <h1 itemprop="name">Nadia's Garden</h1>
    //   <p itemscope ______ ______>
    //     <span itemprop="ratingValue">4.5</span> stars - based on
    //     <span itemprop="reviewCount">120</span> reviews
    //   </p>
    // </section> :',
    //   source: [
    //     { text: 'itemprop="aggregateRating" itemref="http://schema.org/AggregateRating"' },
    //     { text: 'itemprop="aggregateRating" itemtype="http://schema.org/AggregateRating"' },
    //     { text: 'itemid="aggregateRating" itemtype="http://schema.org/AggregateRating"' },
    //     { text: 'itemid="aggregateRating" itemref="http://schema.org/AggregateRating"' },
    //   ],
    //   ok: 1,
    //   link: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemtype',
    // },
    {
      id: '45',
      text: 'Který name atribut se nepoužívá uvnitř značky <meta>?',
      source: [
        { text: 'charset' },
        { text: 'viewport' },
        { text: 'generator' },
        { text: 'author' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/html/html_charset.asp',
    },
    {
      id: '46',
      text: 'Jaké je absolutní hodnota URL stránky s názvem page.html?',
      source: [
        { text: 'http://www.linkedin.com/dir/page.html' },
        { text: 'page.html' },
        { text: 'http://www.linkedin.com/page.html' },
        { text: 'dir/page.html' },
      ],
      ok: 0,
      link: 'https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL',
    },
  ],

  CSS: [
    {
      id: '1',
      text: 'Co znamená zkratka CSS?',
      source: [
        { text: 'Creative Style Sheets' },
        { text: 'Cascading Style Sheets' },
        { text: 'Colorful Style Sheets' },
        { text: 'Cascading Sheets Style' },
      ],
      ok: 1,
      link: 'https://cs.wikipedia.org/wiki/Kask%C3%A1dov%C3%A9_styly',
    },
    {
      id: '2',
      text: 'Který HTML tag značí vestavěný CSS styl?',
      source: [
        { text: '<css>' },
        { text: '<script>' },
        { text: '<div>' },
        { text: '<style>' },
      ],
      ok: 3,
      link: 'https://www.jakpsatweb.cz/css/css-prakticky.html',
    },
    {
      id: '3',
      text: 'Jaká je správná forma odkazu na externí CSS styl?',
      source: [
        { text: '<style src="externi-soubor.css">' },
        {
          text: '<link rel="stylesheet" type="text/css" href="externí-soubor.css"> ',
        },
        { text: '<stylesheet>externi-soubor.css</stylesheet>' },
      ],
      ok: 1,
      link: 'https://www.jakpsatweb.cz/css/css-prakticky.html#externi',
    },
    {
      id: '4',
      text: 'Kde v HTML dokumentu je správné místo pro umístění odkazu na externí CSS styl?',
      source: [
        { text: '1. řádek dokumentu' },
        { text: 'V sekci <body>' },
        { text: 'Na konci dokumentu' },
        { text: 'V sekci <head>' },
      ],
      ok: 3,
      link: 'https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started#adding_css_to_our_document',
    },
    {
      id: '5',
      text: 'Která z těchto možností má správný tvar pro CSS informaci?',
      source: [
        { text: '{body:color=blue(body)}' },
        { text: 'body:color=blue' },
        { text: 'body {color: blue;} ' },
        { text: '{body;color:blue}' },
      ],
      ok: 2,
      link: 'https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Getting_started#styling_html_elements',
    },
    {
      id: '6',
      text: 'Který atribut se používá pro změnu barvy na pozadí?',
      source: [
        { text: 'background-color:' },
        { text: 'backcolor:' },
        { text: 'color:' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/cssref/pr_background-color.asp',
    },
    {
      id: '7',
      text: 'Jak určíte barvu pro všechny nadpisy <h1>',
      source: [
        { text: 'all.h1 {color:red}' },
        { text: 'h1.all {color:red}' },
        { text: 'h1 {color:red}' },
        { text: '#h1 {color:red}' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/cssref/pr_text_color.asp',
    },
    {
      id: '8',
      text: 'Pomocí kterého atributu určíte velikost textu?',
      source: [
        { text: 'text-size' },
        { text: 'text-height' },
        { text: 'font-size' },
        { text: 'font-style' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/cssref/pr_font_font-size.asp',
    },
    {
      id: '9',
      text: 'Jak vytvoříte tučné písmo?',
      source: [
        { text: 'font-weight:bold' },
        { text: 'font:b' },
        { text: 'style:bold' },
        { text: 'font-style:bold' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/cssref/pr_font_weight.asp',
    },
    {
      id: '10',
      text: 'Jak vytvoříte podtrhnuté písmo?',
      source: [
        { text: 'text-decoration:no underline' },
        { text: 'decoration:underline' },
        { text: 'text-decoration:underline' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/cssref/css3_pr_text-decoration-line.asp',
    },
    {
      id: '11',
      text: 'Jak je správná forma zápisu CSS třídy?',
      source: [
        { text: '.jméno-třídy { atribut: hodnota; }' },
        { text: '#jméno-třídy { atribut: hodnota; }' },
        { text: '(jméno-třídy) { atribut: hodnota; }' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/cssref/sel_class.asp',
    },
    {
      id: '12',
      text: 'Který atribut slouží pro určení šířky?',
      source: [{ text: 'height' }, { text: 'size' }, { text: 'width' }],
      ok: 'https://www.w3schools.com/cssref/pr_dim_width.asp',
      link: 2,
    },
    {
      id: '13',
      text: 'Pomocí kterého atributu určíte styl seznamu?',
      source: [
        { text: 'list-style:' },
        { text: 'list-type:' },
        { text: 'style:' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/cssref/pr_list-style.asp',
    },
    {
      id: '14',
      text: 'Jak uděláte, aby každé slovo v textu začínalo automaticky velkým písmenem?',
      source: [
        { text: 'text-transform:uppercase' },
        { text: 'text-transform:capitalize' },
        { text: 'text-transform:lowercase:' },
        { text: 'nelze' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/cssref/pr_text_text-transform.asp',
    },
    {
      id: '15',
      text: 'Lze v CSS upravovat jednotlivé strany u rámečku?',
      source: [
        { text: 'ano' },
        { text: 'ano, ale pouze levou a pravou stranu' },
        { text: 'ano, ale pouze horní a dolní stranu' },
        { text: 'nelze' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/cssref/pr_border.asp',
    },
    {
      id: '16',
      text: 'Jak docílíte toho, aby každé první písmeno odstavce bylo červené?',
      source: [
        { text: 'p::first-letter { color: red; }' },
        { text: 'p:first-letter { color: red; }' },
        { text: 'first-letter::p { color: red; }' },
        { text: 'first-letter:p { color: red; }' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/cssref/sel_firstletter.asp',
    },
   
    {
      id: '17',
      text: 'Jak zaoblíme rohy v blokovém prvku?',
      source: [
        { text: 'corner-curve: 10px' },
        { text: 'border-corner: 10px' },
        { text: 'border-radius: 10px' },
        { text: 'corner-radius: 10px' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/cssref/css3_pr_border-radius.asp',
    },
    {
      id: '18',
      text: 'Která z následujícíchc hodnot není barva?',
      source: [
        { text: 'color: #000' },
        { text: 'color: rgb(0,0,0)' },
        { text: 'color: #000000' },
        { text: 'color: 000000' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/cssref/css_colors.asp',
    },
    {
      id: '19',
      text: 'Jak velká je vertikální mezera mezi dvěma následujícími elementy:<div style="margin-bottom: 2rem;">Div 1</div><div style="margin-top: 2rem;">Div 2</div>',
      source: [
        { text: '2rem' },
        { text: '32px' },
        { text: '64px' },
        { text: '4rem' },
      ],
      ok: 0,
      link: 'https://www.vzhurudolu.cz/prirucka/css3-jednotky',
    },
    {
      id: '20',
      text: 'Jaká jsou klíčová slova pro následující číselné hodnoty: font-weight: 400; font-weight: 700;?',
      source: [
        { text: 'bold; normal' },
        { text: 'normal; bold ' },
        { text: 'light; normal' },
        { text: 'normal; bolder' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/cssref/pr_font_weight.asp',
    },
    {
      id: '21',
      text: 'Kontejner ma šiřku 500px. Jak široké budou sloupce v kódu: .grid { display: grid; grid-template-columns: 50px 1fr 2fr; }?',
      source: [
        { text: '50px, 150px, 300px' },
        { text: '50px, 200px, 300px' },
        { text: '50px, 100px, 200px' },
        { text: '50px, 50px, 100px' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/cssref/css_units.asp',
    },
    {
      id: '22',
      text: 'Chcene-li padding 10px dole a nahoře, 0 px vlevo a vpravo.',
      source: [
        { text: 'padding: 10px 10px 0px 0px; ' },
        { text: 'padding: 10px 0px;' },
        { text: 'padding: 10px 0;' },
        { text: 'padding: 10px 0px 10px 0px;' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/css/css_padding.asp',
    },
    {
      id: '23',
      text: 'Jak nastylujeme prvek na pevné místo uvnitř kontejneru?',
      source: [
        { text: 'position: absolute;' },
        { text: 'display: flex;' },
        { text: 'display: block;' },
        { text: 'float: left;' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/css/css_positioning.asp',
    },
    {
      id: '24',
      text: 'Neplatná hodnota pro styl písma je:',
      source: [
        { text: 'normal' },
        { text: 'italic' },
        { text: 'none' },
        { text: 'oblique' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/cssref/pr_font_font-style.asp',
    },
    {
      id: '25',
      text: 'HTML má na starosti strukturu, CSS:',
      source: [
        { text: 'sémantický význam' },
        { text: 'obsahový význam' },
        { text: 'strukturu dokumentu' },
        { text: 'vzhled   ' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/css/css_intro.asp',
    },
    {
      id: '26',
      text: 'Jak byste měli pojmenovat složku, v níž v projektu uchováváte obrázky?',
      source: [
        { text: 'images' },
        { text: '#images' },
        { text: 'Images' },
        { text: 'my images' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/html/html_filepaths.asp',
    },
    {
      id: '27',
      text: 'Kterým CSS selektorem můžete přepsat pravidla specificity?',
      source: [
        { text: '!elevate!' },
        { text: '*prime' },
        { text: 'override' },
        { text: '!important' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/css/css_important.asp',
    },
    {
      id: '28',
      text: 'Jak barevně odlišíte již navštívený odkaz?',
      source: [
        { text: 'a:visited' },
        { text: 'a:hover' },
        { text: 'a:link' },
        { text: 'a:focus' },
      ],
      ok: 0,
      link: 'https://www.jakpsatweb.cz/css/pseudotridy.html',
    },
    {
      id: '29',
      text: 'Jak upravíte mezery v textu?',
      source: [
        { text: 'font-style' },
        { text: 'text-transform' },
        { text: 'font-variant' },
        { text: 'letter-spacing ' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/cssref/pr_text_letter-spacing.asp',
    },
    {
      id: '30',
      text: 'Chcete-li změnit kurzor s šipky na ruku s ukozaváčkem, použijete:',
      source: [
        { text: '.element {cursor: pointer;} ' },
        { text: '.element {cursor: hand;}' },
        { text: '.element {cursor: move-hand;}' },
        { text: '.element {cursor: pointer-hand;}' },
      ],
      ok: 0,
      link: 'https://developer.mozilla.org/en-US/docs/Web/CSS/cursor',
    },



  ],

  Angličtina: [
    {
      id: '1',
      text: 'Can I park here?',
      source: [
        { text: 'Sorry, I did that. ' },
        { text: 'It is the same place.' },
        { text: 'Only for half an hour.' },
      ],
      ok: 2,
      link: 'https://www.helpforenglish.cz/article/2006061201-modalni-slovesa',
    },
    {
      id: '2',
      text: 'What colour will you paint the office?',
      source: [
        { text: 'I hope it was right. ' },
        { text: 'We can´t decide. ' },
        { text: 'It wasn´t very difficult. ' },
      ],
      ok: 1,
      link: 'http://www.englishpage.com/conditional/conditionalintro.html',
    },
    {
      id: '3',
      text: 'I can´t understand this email.',
      source: [
        { text: 'Would you like some help?  ' },
        { text: 'Don´t you know? ' },
        { text: 'I suppose you can.  ' },
      ],
      ok: 0,
      link: 'http://www.englishpage.com/conditional/conditionalintro.html',
    },
    {
      id: '4',
      text: 'I´d like two tickets for tomorrow night.',
      source: [
        { text: 'How much did you pay?' },
        { text: 'Afternoon and evening. ' },
        { text: 'I´ll just check for you.' },
      ],
      ok: 2,
      link: 'http://www.englishpage.com/verbpage/verbtenseintro.html',
    },
    {
      id: '5',
      text: 'Shall we go to the gym now?',
      source: [
        { text: 'I´m too tired. ' },
        { text: 'It´s very good. ' },
        { text: 'Not at all.' },
      ],
      ok: 0,
      link: 'http://www.englishpage.com/verbpage/simplefuture.html',
    },
    {
      id: '6',
      text: 'His eyes were ...... bad that he couldn´t read the number plate of the car in front.',
      source: [
        { text: 'such' },
        { text: 'too' },
        { text: 'so' },
        { text: 'very' },
      ],
      ok: 2,
      link: 'https://www.helpforenglish.cz/article/2006051201-pleteme-si-so-such',
    },
    {
      id: '7',
      text: 'The company needs to decide ...... and for all what its position is on this point.',
      source: [
        { text: 'here' },
        { text: 'once' },
        { text: 'first' },
        { text: 'finally' },
      ],
      ok: 1,
      link: 'https://www.dictionary.com/browse/once--and--for--all',
    },
    {
      id: '8',
      text: 'Don´t put your cup on the ...... of the table – someone will knock it off.',
      source: [
        { text: 'outside' },
        { text: 'edge' },
        { text: 'boundary' },
        { text: 'border' },
      ],
      ok: 1,
      link: 'http://www.englishpage.com/prepositions/prepositions.html',
    },
    {
      id: '9',
      text: 'I´m sorry - I didn´t ...... to disturb you.',
      source: [
        { text: 'hope' },
        { text: 'think' },
        { text: 'mean' },
        { text: 'suppose' },
      ],
      ok: 2,
      link: 'http://www.englishpage.com/verbpage/verbtenseintro.html',
    },
    {
      id: '10',
      text: 'The singer ended the concert ...... her most popular song.',
      source: [
        { text: 'by' },
        { text: 'with' },
        { text: 'in' },
        { text: 'as' },
      ],
      ok: 1,
      link: 'http://www.englishpage.com/verbpage/verbtenseintro.htmlhttps://www.macmillandictionary.com/dictionary/british/end-with',
    },
    {
      id: '11',
      text: 'Would you mind ...... these plates a wipe before putting them in the cupboard?',
      source: [
        { text: 'making' },
        { text: 'doing' },
        { text: 'getting' },
        { text: 'giving' },
      ],
      ok: 3,
      link: 'https://english.stackexchange.com/questions/421985/mind-action-ing-is-it-correct-for-ask-anything-to-someone/421986',
    },
    {
      id: '12',
      text: 'I was looking forward ...... at the new restaurant, but it was closed.',
      source: [
        { text: 'to eat' },
        { text: 'to have eaten' },
        { text: 'to eating' },
        { text: 'eating' },
      ],
      ok: 2,
      link: 'https://dictionary.cambridge.org/dictionary/english/look-forward-to-sth',
    },
    {
      id: '13',
      text: '...... tired Melissa is when she gets home from work, she always makes time to say goodnight to the children.',
      source: [
        { text: 'Whatever' },
        { text: 'No matter how' },
        { text: 'However much' },
        { text: 'Although' },
      ],
      ok: 1,
      link: 'https://www.wordreference.com/encz/no%20matter%20how',
    },
    {
      id: '14',
      text: 'It was only ten days ago ...... she started her new job.',
      source: [
        { text: 'then' },
        { text: 'since' },
        { text: 'after' },
        { text: 'that' },
      ],
      ok: 3,
      link: 'http://www.englishpage.com/verbpage/simplepast.html',
    },
    {
      id: '15',
      text: 'The shop didn´t have the shoes I wanted, but they´ve ...... a pair specially for me.',
      source: [
        { text: 'booked' },
        { text: 'ordered' },
        { text: 'commanded' },
        { text: 'asked' },
      ],
      ok: 1,
      link: 'http://www.englishpage.com/verbpage/presentperfect.html',
    },
    {
      id: '16',
      text: 'Have you got time to discuss your work now or are you ...... to leave?',
      source: [
        { text: 'thinking' },
        { text: 'round' },
        { text: 'planned' },
        { text: 'about' },
      ],
      ok: 3,
      link: 'https://englishhacker.cz/anglicke-gramaticke-casy-25-vazba-to-be-about-to/',
    },
    {
      id: '17',
      text: 'She came to live here ...... a month ago.',
      source: [
        { text: 'quite' },
        { text: 'beyond' },
        { text: 'already' },
        { text: 'almost' },
      ],
      ok: 3,
      link: 'https://www.merriam-webster.com/dictionary/almost',
    },
    {
      id: '18',
      text: 'Once the plane is in the air, you can ...... your seat belts if you wish.',
      source: [
        { text: 'undress' },
        { text: 'unfasten' },
        { text: 'unlocky' },
        { text: 'untie' },
      ],
      ok: 1,
      link: 'https://www.italki.com/post/question-450204',
    },
    {
      id: '19',
      text: 'I left my last job because I had no ...... to travel.',
      source: [
        { text: 'place' },
        { text: 'position' },
        { text: 'opportunity' },
        { text: 'possibility' },
      ],
      ok: 2,
      link: 'https://grammar.collinsdictionary.com/english-usage/what-is-the-difference-between-possibility-and-opportunity',
    },
    {
      id: '20',
      text: 'It wasn´t a bad crash and ...... damage was done to my car.',
      source: [
        { text: 'little' },
        { text: 'small' },
        { text: 'light' },
        { text: 'mere' },
      ],
      ok: 0,
      link: 'https://www.helpforenglish.cz/forum/thread/523-small-vs-little',
    },
    {
      id: '21',
      text: 'I´d rather you ...... to her why we can´t go.',
      source: [
        { text: 'would explain' },
        { text: 'explained' },
        { text: 'to explain' },
        { text: 'will explain' },
      ],
      ok: 1,
      link: 'https://www.learn-english-today.com/lessons/lesson_contents/grammar/rather.html',
    },
    {
      id: '22',
      text: 'Before making a decision, the leader considered all ...... of the argument.',
      source: [
        { text: 'sides' },
        { text: 'features' },
        { text: 'perspectives' },
        { text: 'shades' },
      ],
      ok: 0,
      link: 'https://comparewords.com/perspective/side',
    },
    {
      id: '23',
      text: 'This new printer is recommended as being ...... reliable.',
      source: [
        { text: 'greatly' },
        { text: 'highly' },
        { text: 'strongly' },
        { text: 'readily' },
      ],
      ok: 1,
      link: 'https://comparewords.com/highly/strongly',
    },
    {
      id: '24',
      text: 'When I realised I had dropped my pen, I decided to ...... my steps.',
      source: [
        { text: 'retrace' },
        { text: 'regress' },
        { text: 'resume' },
        { text: 'return' },
      ],
      ok: 0,
      link: 'https://comparewords.com/retrace/return',
    },
    {
      id: '25',
      text: 'Anne´s house is somewhere in the ...... of the railway station',
      source: [
        { text: 'region' },
        { text: 'quarter' },
        { text: 'vicinity' },
        { text: 'district' },
      ],
      ok: 2,
      link: 'https://comparewords.com/quarter/vicinity',
    },
    {
      id: '26',
      text: 'Why is the HR department sending this email? To: All staff From: HR Department. Please remember that your manager must agree any holiday dates before you complete a form.',
      source: [
        { text: 'to ask staff for some information' },
        { text: 'to explain how something is done' },
        { text: 'to tell managers about a problem' },
      ],
      ok: 1,
      link: 'https://learnenglishteens.britishcouncil.org/skills/reading/beginner-a1-reading/thank-you-email',
    },
    {
      id: '27',
      text: 'I hope I haven´t ...... you any trouble by changing the arrangements.',
      source: [
        { text: 'put' },
        { text: 'caused' },
        { text: 'made' },
        { text: 'done' },
      ],
      ok: 1,
      link: 'http://www.englishpage.com/verbpage/presentperfect.html',
    },
    {
      id: '28',
      text: 'When you come to the meeting, ...... your laptop with you.',
      source: [
        { text: 'take' },
        { text: 'show' },
        { text: 'fetch' },
        { text: 'bring' },
      ],
      ok: 3,
      link: 'https://comparewords.com/bring/take',
    },
    {
      id: '29',
      text: 'I would ...... to stay at home and relax for a change.',
      source: [
        { text: 'rather' },
        { text: 'better' },
        { text: 'prefer' },
        { text: 'enjoy' },
      ],
      ok: 2,
      link: 'https://speakspeak.com/resources/english-grammar-rules/various-grammar-rules/would-rather-versus-would-prefer-and-prefer',
    },
    {
      id: '30',
      text: '...... the step when you go in.',
      source: [
        { text: 'Consider' },
        { text: 'Mind' },
        { text: 'Mind' },
        { text: 'Look' },
      ],
      ok: 1,
      link: 'https://www.macmillandictionary.com/dictionary/british/watch-mind-your-step',
    },
  ],

  Javascript: [
    {
      id: '1',
      text: 'Mezi které HTML tagy vkládáme Javascript?',
      source: [
        { text: '<js> a </js>' },
        { text: '<javascript> a </javascript>' },
        { text: '<script> a </script>' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/js/js_whereto.asp',
    },
    {
      id: '2',
      text: 'Která z těchto možností je správná pro vypsání textu: "Ahoj"?',
      source: [
        { text: '"Ahoj"' },
        { text: 'write:"Ahoj"' },
        { text: 'document.write("Ahoj")' },
        { text: ' write.text("Ahoj") ' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/jsref/met_doc_write.asp',
    },
    {
      id: '3',
      text: 'Kde v HTML dokumentu je správné místo pro umístění Javascriptu',
      source: [
        { text: 'hlavička <head>' },
        { text: 'tělo <body>' },
        { text: 'obojí <head> i <body>' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/js/js_whereto.asp',
    },
    {
      id: '4',
      text: 'Vyberte správný tvar odkazu na externí Javascript.',
      source: [
        { text: '<script href="soubor.js">' },
        { text: '<script src="soubor.js">' },
        { text: '<script name="soubor.js">' },
      ],
      ok: 1,
      link: 'https://www.vzhurudolu.cz/prirucka/html-script',
    },
    {
      id: '5',
      text: 'Vyberte správnou možnost pro zobrazení varovné hlášky.',
      source: [
        { text: 'alertBox("zpráva")' },
        { text: 'alert="zpráva"' },
        { text: 'alerter("zpráva")' },
        { text: 'alert("zpráva")' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/jsref/met_win_alert.asp',
    },
    {
      id: '6',
      text: 'Jak zapisujeme fukce?',
      source: [
        { text: 'function jmenoFunkce(argument) {definice funkce};' },
        { text: 'jmenoFunkce(argument) {definice funkce};' },
        { text: 'function (jmenoFunkce) {definice funkce};' },
        { text: 'jmenoFunkce {definice funkce};' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/js/js_functions.asp',
    },
    {
      id: '7',
      text: 'Která z těchto podmínek je napsána ve správném tvaru?',
      source: [
        { text: 'if (i == 5)' },
        { text: 'if (i = 5)' },
        { text: 'if {i = 5}' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/js/js_if_else.asp',
    },
    {
      id: '8',
      text: 'Jak se tvoří komentáře?',
      source: [
        { text: '<!-- Toto je komentář... -->' },
        { text: '//Toto je komentář...' },
        { text: '/ Toto je komentář...' },
        { text: '!Toto je komentář.../!' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/js/js_comments.asp',
    },
    {
      id: '9',
      text: 'K čemu slouží příkaz while?',
      source: [
        { text: 'nastaví určitý počet opakování cyklu' },
        { text: 'cyklus se neustále opakuje dokud platí stanovená podmínka' },
        { text: 'cyklus se provede pouze jednou, je-li splněna podmínka' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/js/js_loop_while.asp',
    },
    {
      id: '10',
      text: 'Jak se tvoří v Javascriptu pole?',
      source: [
        { text: 'var pole = new Array("jablko","banán","kiwi")' },
        { text: 'var pole = ("jablko","banán","kiwi")' },
        { text: 'var pole = new Array([0]="jablko",[1]="banán",[2]="kiwi")' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/js/js_arrays.asp',
    },
    {
      id: '11',
      text: 'Máme pole: var ovoce = new Array("jablko","hruška","meloun") a necháme vypsat: document.write(ovoce[1]); Která hodnota bude vypsána?',
      source: [{ text: 'jablko' }, { text: 'hruška' }, { text: 'meloun' }],
      ok: 1,
      link: 'https://www.w3schools.com/js/js_arrays.asp',
    },
    {
      id: '12',
      text: 'Jaký příkaz používáme pro přepínače?',
      source: [{ text: 'switch' }, { text: 'selector' }, { text: 'tripper' }],
      ok: 0,
      link: 'https://www.w3schools.com/js/js_switch.asp',
    },
    {
      id: '13',
      text: '"Klikni na tento text" Jaká událost byla použita u tohoto příkladu?.',
      source: [
        { text: 'onDblClick' },
        { text: 'onClick' },
        { text: 'onMouseover' },
        { text: 'onBlur' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/jsref/event_onclick.asp',
    },
    {
      id: '14',
      text: 'Je možné pomocí JavaScriptu vypisovat HTML kódy?',
      source: [{ text: 'ano' }, { text: 'ne' }],
      ok: 0,
      link: 'https://www.w3schools.com/html/html_scripts.asp',
    },
    {
      id: '15',
      text: 'Jak zmněníme obsah HTML elementu v v kódu <p id="demo">This is a demonstration.</p>?',
      source: [
        { text: 'document.getElementByName("p").innerHTML = "Hello World!";' },
        { text: '#demo.innerHTML = "Hello World!";' },
        { text: 'ndocument.getElement("p").innerHTML = "Hello World!";e' },
        { text: 'document.getElementById("demo").innerHTML = "Hello World!";' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/html/html_scripts.asp',
    },
    {
      id: '16',
      text: 'Proměná se v JS deklaruje pomocí slova',
      source: [
        { text: 'new' },
        { text: 'int' },
        { text: 'string' },
        { text: 'var' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/js/js_variables.asp',
    },
    {
      id: '17',
      text: 'Která z následujících možností je v JS tzv. datový typ?',
      source: [
        { text: 'String' },
        { text: 'Number' },
        { text: 'Boolean' },
        { text: 'vVšechny možnosti jsou správněar' },
      ],
      ok: 3,
      link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures',
    },
    {
      id: '18',
      text: 'Jak voláme funkci?',
      source: [
        { text: 'call function myFunction()' },
        { text: 'myFunction()  ' },
        { text: 'call myFunction()' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/js/js_function_call.asp',
    },
    {
      id: '19',
      text: 'Jak napíšem podmínku, v níž i se nerovná 5?',
      source: [
        { text: 'if (i != 5)' },
        { text: 'if (i <> 5)' },
        { text: 'if i <> 5' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/js/js_comparisons.asp',
    },
    {
      id: '20',
      text: 'Vyberte správně zapsané pole v JS:',
      source: [
        { text: 'var colors = (1:"red", 2:"green", 3:"blue")' },
        { text: 'var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")' },
        { text: 'var colors = "red", "green", "blue"' },
        { text: 'var colors = ["red", "green", "blue"]' },
      ],
      ok: 3,
      link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array',
    },
    {
      id: '21',
      text: 'Jak se zaokrouhluje 7.25 na celé číslo?',
      source: [
        { text: 'round(7.25))' },
        { text: 'Math.round(7.25) ' },
        { text: 'rnd(7.25)' },
        { text: 'Math.rnd(7.25)' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/jsref/jsref_round.asp',
    },
    {
      id: '22',
      text: 'Javascript a Java je jedno a totéž:',
      source: [{ text: 'Ano' }, { text: 'Ne' }],
      ok: 1,
      link: 'https://towardsdatascience.com/java-vs-javascript-which-is-the-best-choice-for-2019-a41ee2d3f78d',
    },
    {
      id: '23',
      text: 'K jaké události dojde, když uživatel klikne na prvek HTML?',
      source: [
        { text: 'onchange' },
        { text: 'onclick' },
        { text: 'onmouseover' },
        { text: 'onmouseclick' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/jsref/event_onclick.asp',
    },
    {
      id: '24',
      text: 'Kód Boolean(10 > 9) vrací:',
      source: [{ text: 'true   ' }, { text: 'onfalseclick' }, { text: 'null' }],
      ok: 0,
      link: 'https://www.w3schools.com/js/js_booleans.asp',
    },
    {
      id: '25',
      text: 'Je JS tzv. case-sensitive?',
      source: [{ text: 'Ano' }, { text: 'Ne' }],
      ok: 0,
      link: 'https://www.tutorialspoint.com/Is-JavaScript-a-case-sensitive-language',
    },
    {
      id: '26',
      text: 'Který operátor vrátí true, pokud se dvě porovnávané hodnoty nerovnají?',
      source: [{ text: '<>' }, { text: '~' }, { text: '==!' }, { text: '!==' }],
      ok: 3,
      link: 'https://www.w3schools.com/js/js_operators.asp',
    },
    {
      id: '27',
      text: 'Jak vytovoříme novou funkci s názvem discountPrice?',
      source: [
        {
          text: 'let discountPrice = function(price) { return price * 0.85; };',
        },
        { text: 'let discountPrice(price) { return price * 0.85; };' },
        {
          text: 'let function = discountPrice(price) { return price * 0.85; };',
        },
        { text: 'discountPrice = function(price) { return price * 0.85; };' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/js/js_functions.asp',
    },
    {
      id: '28',
      text: 'Která metoda převádí JSON data na objekt v javascriptu?',
      source: [
        { text: 'JSON.fromString();' },
        { text: 'JSON.parse() ' },
        { text: 'JSON.toObject()' },
        { text: 'JSON.stringify()  ' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/js/js_json_parse.asp',
    },
    {
      id: '29',
      text: 'Které klíčové slovo vytváři chybu?',
      source: [
        { text: 'throw' },
        { text: 'exception' },
        { text: 'catch' },
        { text: 'error' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/js/js_errors.asp',
    },
    {
      id: '30',
      text: 'Vyberte správně pojmenovanou proměnou:',
      source: [
        { text: '5thItem' },
        { text: 'firstName' },
        { text: 'grand total' },
        { text: 'function' },
      ],
      ok: 1,
      link: 'https://www.dummies.com/web-design-development/javascript/naming-javascript-variables/',
    },
  ],

  React: [
    // {
    //   id: '1',
    //   text: 'Pro importovanání komponenety z knihovny React použijete:',
    //   source: [
    //     { text: 'import React.Component from 'react' '},
    //     { text: 'import [ Component ] from 'react' ' },
    //     { text: 'import Component from 'react' ' },
    //     { text: 'import { Component } from 'react' ' },
    //   ],
    //   ok: 3,
    //   link: 'https://www.w3schools.com/react/react_components.asp',
    // },
    {
      id: '2',
      text: '{useState} a {useEffect} jsou tzv.:',
      source: [
        { text: 'React Hooks ' },
        { text: 'DOM' },
        { text: 'JSX element' },
        { text: 'innerHTML' },
      ],
      ok: 0,
      link: 'https://reactjs.org/docs/hooks-intro.html',
    },
    {
      id: '3',
      text: 'Jaká je nejznámější testovací knihovna pro React?',
      source: [
        { text: 'Mocha' },
        { text: 'Chai' },
        { text: 'Sinon' },
        { text: 'iJest    ' },
      ],
      ok: 3,
      link: 'https://jestjs.io/docs/tutorial-react',
    },
    {
      id: '4',
      text: 'Pomocí destrukturalaizace upravte následující kód tak, abyste získali první položku v poli:  const topics = ["cooking", "art", "history"];',
      source: [
        { text: 'const first = ["cooking", "art", "history"]' },
        { text: 'const [] = ["cooking", "art", "history"]' },
        { text: 'const [, first]["cooking", "art", "history"]' },
        { text: 'const [first] = ["cooking", "art", "history"]' },
      ],
      ok: 3,
      link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment',
    },
    {
      id: '5',
      text: 'Co se vypíše do konzole pop zadání tohot kódu: const [, , animal] = ["Horse", "Mouse", "Cat"];console.log(animal);?',
      source: [
        { text: 'Horse' },
        { text: 'Cat    ' },
        { text: 'Mouse' },
        { text: 'undefined' },
      ],
      ok: 1,
      link: 'https://reactjs.org/docs/lists-and-keys.html',
    },
    {
      id: '6',
      text: 'Jak se jmenuje nástroj, který přeměňuje JSX do vanilla Javascriptu?',
      source: [
        { text: 'JSX Editor' },
        { text: 'ReactDOM' },
        { text: 'Browser Buddy' },
        { text: 'Babel' },
      ],
      ok: 3,
      link: 'https://babeljs.io/docs/en/',
    },
    {
      id: '7',
      text: 'Jak se nazývá zpráva ve složených závorkách v následujícím kódu: const message = "Hi there";const element = <p>{message}</p>;?',
      source: [
        { text: 'funkce' },
        { text: 'element' },
        { text: 'props' },
        { text: 'výraz' },
      ],
      ok: 3,
      link: 'https://react.semantic-ui.com/collections/message/',
    },
    {
      id: '8',
      text: 'Destrukturalizujte komponentu Dish: function Dish(props) {return (<h1>{props.name} {props.cookingTime}</h1>);}',
      source: [
        {
          text: 'unction Dish([name, cookingTime]) { return <h1>{name} {cookingTime}</h1>; }',
        },
        {
          text: 'function Dish({name, cookingTime}) { return <h1>{name} {cookingTime}</h1>; } ',
        },
        {
          text: 'function Dish(props) { return <h1>{name} {cookingTime}</h1>; }',
        },
        {
          text: 'function Dish(...props) { return <h1>{name} {cookingTime}</h1>; }',
        },
      ],
      ok: 1,
      link: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment',
    },
    {
      id: '9',
      text: 'Který atribut nahrazuje innerHTML v DOM?',
      source: [
        { text: 'injectHTML' },
        { text: 'dangerouslySetInnerHTML' },
        { text: 'weirdSetInnerHTML' },
        { text: 'strangeHTML' },
      ],
      ok: 1,
      link: 'https://reactjs.org/docs/dom-elements.html',
    },
    {
      id: '10',
      text: 'Jak se nazývá uživatelské rozhraní, které se ukládá do paměti a synchronizuje se se "skutečným" DOM?',
      source: [
        { text: 'virtual DOM ' },
        { text: 'DOML' },
        { text: 'virtual elementsL' },
        { text: 'shadow DOM' },
      ],
      ok: 0,
      link: 'https://reactjs.org/docs/faq-internals.html',
    },
    {
      id: '11',
      text: 'V následujícím kódu se nic nevykresluje. Co s tím? const Heading = () => {<h1>Hello!</h1>;};',
      source: [
        { text: 'Přidáme render funkce' },
        {
          text: 'Složené závorky změníme na normální, nebo vložíme return před h1DOML',
        },
        { text: 'h1 přemístíme do jiné komponenety' },
        { text: 'h1 obalíme divem' },
      ],
      ok: 1,
      link: 'https://www.robinwieruch.de/react-function-component#react-function-component-example',
    },
    {
      id: '12',
      text: 'onstantu vytvoříme pomocí:',
      source: [
        { text: 'const  ' },
        { text: 'let' },
        { text: 'constant' },
        { text: 'var' },
      ],
      ok: 0,
      link: 'https://stackoverflow.com/questions/40825010/const-or-let-in-react-component',
    },
    {
      id: '13',
      text: 'Jak se nazývá komponeneta v Reactu, která vychytává javascriptové chyby v komponentě podřízené rodiči?',
      source: [
        { text: 'error bosses' },
        { text: 'error catchers' },
        { text: 'error helpers' },
        { text: 'error boundaries ' },
      ],
      ok: 3,
      link: 'https://reactjs.org/docs/error-boundaries.html',
    },
    {
      id: '14',
      text: 'Jakou lifecycle metodou získáváme data z class komponent?',
      source: [
        { text: 'constructor' },
        { text: 'componentDidMount   ' },
        { text: 'componentWillReceiveProps' },
        { text: 'componentWillMount ' },
      ],
      ok: 2,
      link: 'https://reactjs.org/docs/react-component.html',
    },
    {
      id: '15',
      text: 'Proč se v Reactu používá ref?',
      source: [
        { text: 'pro přímý přístup do DOM node' },
        { text: 'pro odkaz an jiný JS soubor' },
        { text: 'pro zavolání funkce' },
        { text: 'pro provázání funkcí' },
      ],
      ok: 0,
      link: 'https://reactjs.org/docs/refs-and-the-dom.html',
    },
    {
      id: '16',
      text: 'Jaký balíček obsahuje funkci render(), která vykresluje element z React do DOM?',
      source: [
        { text: 'React' },
        { text: 'ReactDOM' },
        { text: 'Render' },
        { text: 'DOM' },
      ],
      ok: 1,
      link: 'https://reactjs.org/docs/react-dom.html',
    },
    // {
    //   id: '17',
    //   text:  'Jaký tzv. Hook bychom použili v Reactu k aktualizaci titulku stránky?',
    //   source: [
    //     { text: 'useEffect(function updateTitle() { document.title = name + ' ' + lastname; });' },
    //     { text: 'useEffect(() => { title = name + ' ' + lastname; });' },
    //     { text: 'useEffect(function updateTitle() { name + ' ' + lastname; });' },
    //     { text: 'useEffect(function updateTitle() { title = name + ' ' + lastname; });' },
    //   ],
    //   ok: 0,
    //   link: 'https://reactjs.org/docs/hooks-effect.html',
    // },ˇ
    {
      id: '18',
      text: 'V tomto kódu se handleClick volá místo toho, aby odkazoval. Jaký je správný zápis? <button onClick={this.handleClick()}>Click this</button>',
      source: [
        {
          text: '<button onClick={this.handleClick.bind(handleClick)}>Click this</button>',
        },
        { text: '<button onClick={handleClick()}>Click this</button>' },
        { text: '<button onClick={this.handleClick}>Click this</button> ' },
        { text: '<button onclick={this.handleClick}>Click this</button>' },
      ],
      ok: 2,
      link: 'https://reactjs.org/docs/handling-events.html',
    },
    {
      id: '19',
      text: 'Z jaké knihovny získáváme funkci fetch()?',
      source: [
        { text: 'FetchJS' },
        { text: 'ReactDOM' },
        { text: 'Z žádné, fetch() se zobrazuje ve většině prohlížečů' },
        { text: 'React' },
      ],
      ok: 2,
      link: 'https://reactjs.org/docs/faq-ajax.html',
    },
    {
      id: '20',
      text: 'Máme kód const greeting = isLoggedIn ? <Hello /> : null; Kdy se zobrazí komponenta Hello?',
      source: [
        { text: 'nikdy' },
        { text: 'když je isLoggedIn true' },
        { text: 'když se uživatel přihlásí' },
        { text: 'když zavoláme funkci Hello' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/react/react_components.asp',
    },
    // {
    //   id: '21',
    //   text:  'Máme kód ReactDOM.render(<Message orderNumber="16" />, document.getElementById('root'));. Jaký datový typ je orderNumber?',
    //   source: [
    //     { text: 'string  '},
    //     { text: 'boolean' },
    //     { text: 'object' },
    //     { text: 'number' },
    //   ],
    //   ok: 0,
    //   link: 'https://jsx.github.io/doc/typeref.html',
    // },
    {
      id: '22',
      text: 'V kódu const element = <h1 style={ backgroundColor: "blue" }>Hi</h1>; jsme přidali style k h1, ale v konzoli se nám zobrazuje error, jak ho spravíme?',
      source: [
        {
          text: 'const element = <h1 style="backgroundColor: "blue""}>Hi</h1>;',
        },
        { text: 'const element = <h1 style=>Hi</h1>;' },
        { text: 'const element = <h1 style={blue}>Hi</h1>;' },
        { text: 'const element = <h1 style="blue">Hi</h1>;' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/react/react_css.asp',
    },
    {
      id: '23',
      text: 'Která funkce se používá k aktualizaci stavových proměnných v React komponentě?',
      source: [
        { text: 'replaceState' },
        { text: 'refreshState' },
        { text: 'updateState' },
        { text: 'setState   ' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/react/react_state.asp',
    },
    {
      id: '24',
      text: 'Máme kód const Star = ({ selected = false }) => <Icon color={selected ? "red" : "grey"} />;. Jaká je defaultní barva pro star?',
      source: [
        { text: 'black' },
        { text: 'red' },
        { text: 'grey  ' },
        { text: 'white   ' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/react/react_css.asp',
    },
    {
      id: '25',
      text: ' React vytvoříme pomocí příkazu:',
      source: [
        { text: 'px create-react-app <project-name>' },
        { text: 'npx install-react-app <project-name>' },
        { text: 'npx run-react-app <project-name>' },
        { text: 'npx create-react-js-app <project-name>' },
      ],
      ok: 0,
      link: 'https://reactjs.org/docs/create-a-new-react-app.html',
    },
    {
      id: '26',
      text: 'Události v Reactu jsou podobné:',
      source: [
        { text: 'událostem u prvků DOM v JS' },
        { text: 'funkcím v JS' },
        { text: 'proměnným v JS' },
        { text: 'cyklům v JS' },
      ],
      ok: 0,
      link: 'https://reactjs.org/docs/handling-events.html',
    },
    {
      id: '27',
      text: 'React byl vytvořen společností:',
      source: [
        { text: 'Seznam' },
        { text: 'Facebook  ' },
        { text: 'Google' },
        { text: 'IBM' },
      ],
      ok: 1,
      link: 'https://thenewstack.io/javascripts-history-and-how-it-led-to-reactjs/',
    },
    {
      id: '28',
      text: 'Události v Reactu se pojmenovávají stylem:',
      source: [
        { text: 'camelCase   ' },
        { text: 'snake_case  ' },
        { text: 'kebab-case' },
        { text: 'studly caps' },
      ],
      ok: 0,
      link: 'https://reactjs.org/docs/introducing-jsx.html',
    },
    {
      id: '29',
      text: 'Máme kód const name = "Rachel"; const age = 31; const person = { name, age }; console.log(person);. Co se nám vypíše do konzole?',
      source: [
        { text: ' `` ' },
        { text: '{name: "Rachel", age: 31} ' },
        { text: '{person: "Rachel", person: 31}}' },
        { text: '{person: {name: "Rachel", age: 31}}' },
      ],
      ok: 1,
      link: 'https://reactjs.org/docs/introducing-jsx.html',
    },
    {
      id: '30',
      text: 'Mám kód pro tlačítko A (<button onClick={this.handleClick}>Click Me</button>) a kód pro tlačítko B (<button onClick={event => this.handleClick(event)}>Click Me</button>). Jaký je mezi nimi rozdíl?',
      source: [
        { text: 'Po kliknutí nemá tlačítko A přístup k události' },
        { text: 'Tlačítko B nespustí this.handleClick' },
        { text: 'Tlačítko A nespustí this.handleClick' },
        { text: 'Žádný  ' },
      ],
      ok: 3,
      link: 'https://reactjs.org/docs/handling-events.html',
    },
  ],

  GIT: [
    {
      id: '1',
      text: 'Jak ověřite, že máte aktuální verzi GITu?',
      source: [
        { text: 'git –v' },
        { text: 'git –version' },
        { text: 'git –option' },
        { text: 'git –current' },
      ],
      ok: 1,
      link: 'https://stackoverflow.com/questions/8475958/how-can-i-find-out-what-version-of-git-im-running',
    },
    {
      id: '2',
      text: 'GIT je:',
      source: [
        { text: 'distribuovaný systém správy verzí ' },
        { text: 'framework' },
        { text: 'webový prohlížeč' },
        { text: 'programovací jazyk' },
      ],
      ok: 0,
      link: 'https://git-scm.com/book/cs/v2/%C3%9Avod-Spr%C3%A1va-verz%C3%AD',
    },
    {
      id: '3',
      text: 'Který z následujícich webů neposkytuje hostování zdrojových kódů v repozitářích postavených na GITu:',
      source: [
        { text: 'GitHub' },
        { text: 'GitLab' },
        { text: 'Bitbucket' },
        { text: 'Facebook    ' },
      ],
      ok: 3,
      link: 'https://en.wikipedia.org/wiki/Git',
    },
    {
      id: '4',
      text: 'V konzoli se po příkazu git remote -v ukáže:',
      source: [
        { text: 'seznam vzdálených úložišť a jejich URL adres' },
        { text: 'aktuální verze gitu, kterou používáte' },
        { text: 'editor pro úpravy vzdálených úložišť' },
        { text: 'posledních 5 verzí gitu, které jste nainstalovali' },
      ],
      ok: 0,
      link: 'https://www.git-tower.com/learn/git/commands/git-remote/',
    },
    {
      id: '5',
      text: 'Který příkaz použijete, chcete-li aby se byla aplikovaelná do celého git prostředí?',
      source: [
        { text: '--all' },
        { text: '--master' },
        { text: '--global' },
        { text: '--update' },
      ],
      ok: 2,
      link: 'https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration',
    },
    {
      id: '6',
      text: 'Kterým přikezem si stáhnete repozitář z GitHubu do počítače?',
      source: [
        { text: 'git push' },
        { text: 'git fork' },
        { text: 'git clone' },
        { text: 'git commit' },
      ],
      ok: 2,
      link: 'https://git-scm.com/book/cs/v2/Z%C3%A1klady-pr%C3%A1ce-se-syst%C3%A9mem-Git-Z%C3%ADsk%C3%A1n%C3%AD-repozit%C3%A1%C5%99e-Git',
    },
    {
      id: '7',
      text: 'Jaký je opak příkazu git clone, který místo stahování kódu z GitHubu nahraje změny a kód zpět do GitHubu?',
      source: [
        { text: 'git push' },
        { text: 'git add' },
        { text: 'git upload' },
        { text: 'git status' },
      ],
      ok: 0,
      link: 'https://git-scm.com/docs/git-push/en',
    },
    {
      id: '8',
      text: 'Jakým příkazen zkontrolujete stav repozitáře?',
      source: [
        { text: 'git check' },
        { text: 'git status' },
        { text: 'git commit' },
        { text: 'git diff' },
      ],
      ok: 1,
      link: 'https://github.com/git-guides/git-status',
    },
    {
      id: '9',
      text: 'Jakým príkazem připravíte soubor k zapsání?',
      source: [
        { text: 'git stage' },
        { text: 'git commit' },
        { text: 'git add  ' },
        { text: 'git reset' },
      ],
      ok: 2,
      link: 'https://git-scm.com/book/cs/v2/Z%C3%A1klady-pr%C3%A1ce-se-syst%C3%A9mem-Git-Nahr%C3%A1v%C3%A1n%C3%AD-zm%C4%9Bn-do-repozit%C3%A1%C5%99e',
    },
    {
      id: '10',
      text: 'Jakým příkazem uložíte/zapíšete aktuální stav kódu do ovládacího prvku verze gitu?',
      source: [
        { text: 'git commit' },
        { text: 'git stage' },
        { text: 'git add' },
        { text: 'git init' },
      ],
      ok: 0,
      link: 'https://www.git-tower.com/learn/git/commands/git-commit/',
    },
    {
      id: '11',
      text: 'Jak zapíšete zprávu do commitu?',
      source: [
        { text: 'git message "First code"' },
        { text: 'git git add "First code"' },
        { text: 'git commit "First code"' },
        { text: 'git commit -m "First code"' },
      ],
      ok: 3,
      link: 'https://www.git-tower.com/learn/git/commands/git-commit/',
    },
    {
      id: '12',
      text: 'Kterým příkazem inicializujeme nový git reppozitář?',
      source: [
        { text: 'git new' },
        { text: 'git add' },
        { text: 'git init' },
        { text: 'git initialize' },
      ],
      ok: 2,
      link: 'https://github.com/git-guides/git-init',
    },
    {
      id: '13',
      text: 'Který příkaz připraví nový soubor nebo přidá změny k zapsání?',
      source: [
        { text: 'git stage' },
        { text: 'git add' },
        { text: 'git filenamen' },
        { text: 'žádný' },
      ],
      ok: 1,
      link: 'https://git-scm.com/book/cs/v2/Z%C3%A1klady-pr%C3%A1ce-se-syst%C3%A9mem-Git-Nahr%C3%A1v%C3%A1n%C3%AD-zm%C4%9Bn-do-repozit%C3%A1%C5%99e',
    },
    {
      id: '14',
      text: 'Jaký příkaz zapíše změny připravené k zapsání?',
      source: [
        { text: 'git commit' },
        { text: 'git comment' },
        { text: 'git lockdown' },
        { text: 'git push' },
      ],
      ok: 0,
      link: 'https://www.git-tower.com/learn/git/commands/git-commit/',
    },
    {
      id: '15',
      text: ' Který příkaz připraví nový soubor .txt nebo přidá změny k zapsání',
      source: [
        { text: 'git add *.txt' },
        { text: 'git add *.text' },
        { text: 'git add -a .txt' },
        { text: 'git add - *.txt' },
      ],
      ok: 0,
      link: 'https://git-scm.com/docs/git-add',
    },
    {
      id: '16',
      text: 'K vytvoření nové větve použijeme příkaz',
      source: [
        { text: 'git branch' },
        { text: 'git -b' },
        { text: 'git new branch' },
        { text: 'git checkout branch' },
      ],
      ok: 0,
      link: 'https://git-scm.com/book/cs/v2/V%C4%9Btve-v-syst%C3%A9mu-Git-V%C4%9Btve-v-kostce',
    },
    {
      id: '17',
      text: 'Abychom si udělali přehled o historii kódu, použijeme',
      source: [
        { text: 'git log --oneline' },
        { text: 'git reset --hard' },
        { text: 'git log --author=""' },
        { text: 'git rebase' },
      ],
      ok: 0,
      link: 'https://git-scm.com/docs/git-log',
    },
    {
      id: '18',
      text: 'Pro odstranění nesledovaných souborů zvolíme příkaz:',
      source: [
        { text: 'git commit' },
        { text: 'git clean -f ' },
        { text: 'git clean' },
        { text: 'git reset' },
      ],
      ok: 1,
      link: 'https://www.w3docs.com/learn-git/git-clean.html',
    },
    {
      id: '19',
      text: 'Který příkaz stahuje všechny objekty a odkazy z daného repozitáře?',
      source: [
        { text: 'git config --list' },
        { text: 'git help' },
        { text: 'git fetch  ' },
        { text: 'git log -n' },
      ],
      ok: 2,
      link: 'https://git-scm.com/book/cs/v2/Z%C3%A1klady-pr%C3%A1ce-se-syst%C3%A9mem-Git-Pr%C3%A1ce-se-vzd%C3%A1len%C3%BDmi-repozit%C3%A1%C5%99i',
    },
    {
      id: '20',
      text: 'Který příkaz porovnává vybrané větve?',
      source: [
        { text: 'git diff ... ' },
        { text: 'git merge' },
        { text: 'git blame -L' },
        { text: 'git push --tags' },
      ],
      ok: 2,
      link: 'https://git-scm.com/docs/git-diff/en',
    },
    {
      id: '21',
      text: 'Který příkaz přjmenovává konkrétní větev?',
      source: [
        { text: 'git remote rm' },
        { text: 'git branch -m ' },
        { text: 'git branch -D (CAPS)' },
        { text: 'git rebase' },
      ],
      ok: 1,
      link: 'https://git-scm.com/book/cs/v2/V%C4%9Btve-v-syst%C3%A9mu-Git-Vzd%C3%A1len%C3%A9-v%C4%9Btve',
    },
    {
      id: '22',
      text: 'Který příkaz zobrazí zapsané změny (commits)??',
      source: [
        { text: 'git branch' },
        { text: 'git remote -v' },
        { text: ' git log -p  ' },
        { text: 'git log' },
      ],
      ok: 2,
      link: 'https://www.toolsqa.com/git/git-log/',
    },
    {
      id: '23',
      text: 'Který z následujícíh příkazových řádků se používá pro komnikaci s GITem?',
      source: [
        { text: ' Git Bash ' },
        { text: ' GitHub' },
        { text: ' Git Boot' },
        { text: ' Git Lab' },
      ],
      ok: 0,
      link: 'https://www.atlassian.com/git/tutorials/git-bash',
    },
    {
      id: '24',
      text: 'Chcete-li, aby se změny ve vzdáleném repozitáři promítly i v lokálním repoziráři, zvolíte příkaz git pull:',
      source: [{ text: 'Ano' }, { text: 'Ne' }],
      ok: 0,
      link: 'https://github.com/git-guides/git-pull',
    },
    {
      id: '25',
      text: 'Pracujete-li na projektu v temu a nechcete, aby se vámi provede změny dotkly kódu vašich kolegů, zvolíte příkaz:',
      source: [
        { text: 'the root ' },
        { text: 'a tag' },
        { text: 'the trunk' },
        { text: 'žádný z výše uvedených' },
      ],
      ok: 3,
      link: 'https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History',
    },
    {
      id: '26',
      text: 'Která z následujícíh možností není součástí datové struktury GITu?',
      source: [
        { text: 'Branch pointer' },
        { text: 'Body element' },
        { text: 'Commit object' },
        { text: 'Head pointer' },
      ],
      ok: 1,
      link: 'https://medium.com/swlh/data-structures-used-in-git-implementation-a2c95bf4135e',
    },
    {
      id: '27',
      text: ' GIT je systém ___ generace verzovací správy.',
      source: [
        { text: 'druhé' },
        { text: 'třetí   ' },
        { text: 'páté' },
        { text: 'šesté' },
      ],
      ok: 1,
      link: 'https://initialcommit.com/blog/Technical-Guide-VCS-Internals',
    },
    {
      id: '28',
      text: 'Hlavní cíl GITu je:',
      source: [
        { text: 'rychlost' },
        { text: 'integrita dat' },
        { text: 'podpora nelineárních postupů' },
        { text: 'všechno vše uvedené' },
      ],
      ok: 3,
      link: 'https://zdrojak.cz/clanky/paty-duvod-proc-zvolit-git-zkusenosti-uzivatelu-gitu/',
    },
    {
      id: '29',
      text: 'V jakém jazyce je GIT napsaný?',
      source: [
        { text: 'C' },
        { text: 'HTML' },
        { text: 'PHP' },
        { text: 'C++' },
      ],
      ok: 0,
      link: 'https://en.wikipedia.org/wiki/Git',
    },
    {
      id: '30',
      text: 'Který příkaz označí daný commit?',
      source: [
        { text: 'git checkout [branch name]' },
        { text: 'git show [commit]' },
        { text: 'git tag [commitID]  ' },
        { text: 'git rm [file]' },
      ],
      ok: 2,
      link: 'https://git-scm.com/book/cs/v2/Z%C3%A1klady-pr%C3%A1ce-se-syst%C3%A9mem-Git-Pou%C5%BE%C3%ADv%C3%A1n%C3%AD-zna%C4%8Dek',
    },
  ],

  grafika: [
    {
      id: '1',
      text: 'Bitmapová grafika se často používá pro:',
      source: [
        { text: 'Fotografie a web' },
        { text: 'Výkresy' },
        { text: 'Tvorbu loga' },
        { text: 'Flash animace' },
      ],
      ok: 0,
      link: 'https://cs.wikipedia.org/wiki/Rastrov%C3%A1_grafika',
    },
    {
      id: '2',
      text: 'Které z programů patří mezi bitmapové editory?',
      source: [
        { text: 'Inkscape a CorelDraw' },
        { text: 'Illustrator a InDesign' },
        { text: 'Photoshop a Gimp' },
        { text: 'Scribus a Flash' },
      ],
      ok: 2,
      link: 'https://cs.wikipedia.org/wiki/Bitmapov%C3%BD_grafick%C3%BD_editor',
    },
    {
      id: '3',
      text: 'Mezi nejčastější bitmapové formáty patří:',
      source: [
        { text: '.JPG .GIF .PNG' },
        { text: '.CDR .AI .INDD' },
        { text: '.EPS .SWF .SVG' },
        { text: '.PDF .PS .DWG' },
      ],
      ok: 0,
      link: 'https://cs.wikipedia.org/wiki/Bitmapov%C3%BD_grafick%C3%BD_editor',
    },
    {
      id: '4',
      text: 'V jakých jednotách zadáte velikost bitmapové obrazu pro web?',
      source: [
        { text: 'v centimetrech' },
        { text: 'v procentech' },
        { text: 'v pixelech' },
        { text: 'v milimetrech' },
      ],
      ok: 2,
      link: 'https://cs.wikipedia.org/wiki/BMP',
    },
    {
      id: '5',
      text: 'Jaké je v vhodné rozlišení obrazu pro web - pro monitor (PPI):',
      source: [{ text: '300 ppi' }, { text: '150 ppi' }, { text: '72 ppi' }],
      ok: 2,
      link: 'https://www.webprezent.cz/navody/obrazky-pro-web-optimalni-formaty-velikosti-a-programy-pro-upravy/',
    },
    {
      id: '6',
      text: 'Co znamená zkratka PPI:',
      source: [
        { text: 'Pixels Per Inch' },
        { text: 'Puntíků Pro Internet' },
        { text: 'Points Per Image' },
        { text: 'Pixels Per Image' },
      ],
      ok: 2,
      link: 'https://tech-lib.eu/definition/ppi.html',
    },
    {
      id: '7',
      text: 'Jaké barvy (barevný model) je vhodné používat pro web:',
      source: [
        { text: 'RGB' },
        { text: 'CMYK' },
        { text: 'Pantone' },
        { text: 'LAB' },
      ],
      ok: 0,
      link: 'https://www.jakpsatweb.cz/barvy-zapis.html#rgb',
    },
    {
      id: '8',
      text: 'Rozlišení FULL HD odpovídá obrazu:',
      source: [
        { text: '800x600 px' },
        { text: '1024x768 px' },
        { text: '125x1024 px' },
        { text: '1920x1080 px' },
      ],
      ok: 3,
      link: 'https://www.vzhurudolu.cz/prirucka/rozliseni-displeje',
    },
    {
      id: '9',
      text: 'Kolik barev obsahuje 8 bitový obraz?',
      source: [
        { text: '256 barev' },
        { text: '1,67 mil. barev' },
        { text: '16 barev' },
        { text: 'jiný počet ' },
      ],
      ok: 0,
      link: 'https://helpx.adobe.com/cz/photoshop/using/bit-depth.html',
    },
    {
      id: '10',
      text: 'Z jakých barev je složen model CMYK?',
      source: [
        { text: 'azurová, purpurová, žlutá a černá' },
        { text: 'červená, zelená a modrá' },
        { text: 'červená, žlutá, modrá, černá' },
        { text: 'jiné barvy' },
      ],
      ok: 0,
      link: 'https://cs.wikipedia.org/wiki/CMYK',
    },
    {
      id: '11',
      text: 'Lze použít formát .PDF pro bitmapovou i vektorovou grafiku?',
      source: [{ text: 'ano' }, { text: 'ne' }],
      ok: 0,
      link: 'https://acrobat.adobe.com/cz/cs/acrobat/about-adobe-pdf.html',
    },
    {
      id: '12',
      text: 'Které z uvedených programů jsou Opensource?',
      source: [
        { text: 'Inkscape - Gimp - Scribus' },
        { text: 'Photoshop - Illustrator - InDesign ' },
        { text: 'Corel Draw - Corel Photo-Paint' },
      ],
      ok: 0,
      link: 'https://artster.cz/graficke-programy/',
    },
    {
      id: '13',
      text: 'Mohu si z internetu stáhnou libovolnou fotografii a použít jí např. na web?',
      source: [{ text: 'ano' }, { text: 'ne' }],
      ok: 1,
      link: 'https://www.finance.cz/528593-obrazky-a-fotky-na-internetu/',
    },
    {
      id: '14',
      text: 'Co znamená licence Creative Commons (zkratka CC)?',
      source: [
        { text: 'soubor pravidel pro sdílení díla' },
        { text: 'soubor grafických programů' },
        { text: 'produkt firmy Adobe' },
        { text: 'žádná taková licence neexistuje ' },
      ],
      ok: 2,
      link: 'https://www.finance.cz/528593-obrazky-a-fotky-na-internetu/#Foto%20zdarma',
    },
  ],
  Bootstrap: [
    {
      id: '1',
      text: 'V Bootstrapu se uplatňuje tzv mobile-first přístup',
      source: [
        { text: 'Ano   ' },
        { text: 'Ne' },
  
      ],
      ok: 0,
      link: 'https://getbootstrap.com/docs/4.1/extend/approach/',
    },
    {
      id: '2',
      text: 'Která třída zabírá v Bootstrapu pouze určitou šířku stránky ?',
      source: [
        { text: '.container ' },
        { text: '.container-fixed' },
        { text: '.container-fluid' },
        { text: '.container-width' },
      ],
      ok: 0,
      link: 'https://getbootstrap.com/docs/5.0/layout/containers/',
    },
    {
      id: '3',
      text: 'Která třída zabírá celou šířku stránky?',
      source: [
        { text: '.container-fixed ' },
        { text: '..container-fluid ' },
        { text: '.container' },
        { text: '.container-width' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/bootstrap4/bootstrap_containers.asp',
    },
    {
      id: '4',
      text: 'Kolik sloupců má Bootstrap grid?',
      source: [
        { text: '3' },
        { text: '12' },
        { text: '6' },
        { text: '9' },
      ],
      ok: 1,
      link: 'https://getbootstrap.com/docs/4.0/layout/grid/',
    },
    {
      id: '5',
      text: 'Která třída nastyluje tabulku na tzv. zebra-stripes?',
      source: [
        { text: '.even and .odd' },
        { text: '.table-striped' },
        { text: '.table-zebra' },
        { text: '.table-bordered' },
      ],
      ok: 1,
      link: 'https://www.w3schools.com/bootstrap/bootstrap_ref_css_tables.asp',
    },
    {
      id: '6',
      text: 'Která třída nastyluje obrázek do kruhu?',
      source: [
        { text: '.img-rounded' },
        { text: '.img-thumbnail' },
        { text: '.img-round' },
        { text: '.img-circle' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/bootstrap/bootstrap_ref_css_images.asp',
    },
    {
      id: '7',
      text: 'Kterou třídou vytvoříme extra velké okno?',
      source: [
        { text: '.container' },
        { text: '.jumbotron ' },
        { text: '.bigbox' },
        { text: '.flexbox' },
      ],
      ok: 1,
      link: 'https://getbootstrap.com/docs/4.0/components/jumbotron/',
    },
    {
      id: '8',
      text: 'Kterou třídou vytvoříme veké tlačítko?',
      source: [
        { text: '.btn-lg' },
        { text: '.btn-l' },
        { text: '.btn-xl' },
        { text: '.btn-large' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/bootstrap/bootstrap_buttons.asp',
    },
    {
      id: '9',
      text: 'Kterou třídou vytvoříme skupinu tlačítek?',
      source: [
        { text: '.group-button' },
        { text: '.btn-group' },
        { text: '.button-group' },
        { text: '.group-btn' },
      ],
      ok: 1,
      link: 'https://getbootstrap.com/docs/4.0/components/button-group/',
    },
    {
      id: '10',
      text: 'Jak vložíme ikonu pro vyhledávání?',
      source: [
        { text: '<span class="glyphicon glyphicon-search"></span>' },
        { text: '<span class="glyph glyph-search"></span>' },
        { text: '<span class="glyphicon search"></span>' },
        { text: '<span class="glyphicon-search"></span>' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/bootstrap/bootstrap_glyphicons.asp',
    },
    {
      id: '11',
      text: 'Kterou třídou vytvoříme badge?',
      source: [
        { text: '.tag' },
        { text: '.label' },
        { text: '.badge ' },
        { text: '.flag' },
      ],
      ok: 2,
      link: 'https://getbootstrap.com/docs/4.0/components/badge/',
    },
    {
      id: '12',
      text: 'Jak vytvoříme stránkování?',
      source: [
        { text: '.pagination' },
        { text: '.page' },
        { text: '.pages' },
        { text: '..navigation' },
      ],
      ok: 0,
      link: 'https://www.w3schools.com/bootstrap4/bootstrap_pagination.asp',
    },
    {
      id: '13',
      text: 'Jak vytvoříme základní seznam?',
      source: [
        { text: '.group-list' },
        { text: '.grouped-list' },
        { text: '.list-group ' },
        { text: '.list-groups ' },
      ],
      ok: 2,
      link: 'https://getbootstrap.com/docs/4.0/components/list-group/',
    },
    {
      id: '14',
      text: 'Která třída přidá do panulu nadpis?',
      source: [
        { text: '.panel-header' },
        { text: '.panel-head' },
        { text: '.panel-footer' },
        { text: '.panel-heading' },
      ],
      ok: 3,
      link: 'https://www.w3schools.com/bootstrap/bootstrap_panels.asp',
    },
    {
      id: '15',
      text: 'Jak vytvoříme dropdown menu?',
      source: [
        { text: '.dropdown ' },
        { text: '.dropdown-list' },
        { text: '.select' },
        { text: '.dropup' },
      ],
      ok: 0,
      link: 'https://getbootstrap.com/docs/4.0/components/dropdowns/',
    },
    {
      id: '16',
      text: 'Tlačítka pro navigaci vytvoříme pomocí:',
      source: [
        { text: '<ul class="nav nav-navbar">' },
        { text: '<ul class="nav tabs">' },
        { text: '.<ul class="navigation-tabs">' },
        { text: '.<ul class="nav nav-tabs">' },
      ],
      ok: 3,
      link: 'https://getbootstrap.com/docs/4.0/components/navs/',
    },
    {
      id: '17',
      text: 'Navigační lištu vytoříme pomocí:',
      source: [
        { text: '<nav class="nav navbar">' },
        { text: '<nav class="navbar navbar-default"> ' },
        { text: '<nav class="navigationbar navbar-default">' },
        { text: '<nav class="navbar default-navbar">' },
      ],
      ok: 1,
      link: 'https://getbootstrap.com/docs/4.0/components/navbar/',
    },
    {
      id: '18',
      text: 'Černou navigační lištu vytoříme pomocí:',
      source: [
        { text: '.navbar-black' },
        { text: '.navbar-default' },
        { text: '.navbar-inverse' },
        { text: '.navbar-dark' },
      ],
      ok: 2,
      link: 'https://www.w3schools.com/bootstrap/bootstrap_navbar.asp',
    },
    {
      id: '19',
      text: 'Který plugin používáme k vytvoření pohyblivých elementů, např. slideshow?',
      source: [
        { text: 'Orbit' },
        { text: 'Slideshow' },
        { text: 'Scrollspy' },
        { text: 'Carousel' },
      ],
      ok: 3,
      link: 'https://getbootstrap.com/docs/4.0/components/carousel/',
    },
    {
      id: '20',
      text: 'Dialogové okno vytvoříme pomocí:',
      source: [
        { text: 'Dialog Box' },
        { text: 'Popup' },
        { text: 'Window' },
        { text: 'Modal    ' },
      ],
      ok: 3,
      link: 'https://getbootstrap.com/docs/4.0/components/modal/',
    },
    {
      id: '21',
      text: 'Rychlou nápovědu získáme pomocí:',
      source: [
        { text: 'Dialog Box' },
        { text: 'Tooltip' },
        { text: 'Modal' },
        { text: 'Popup' },
      ],
      ok: 1,
      link: 'https://getbootstrap.com/docs/4.0/components/tooltips/',
    },
    {
      id: '22',
      text: 'Která kontextová třída označuje úspěšnou nebo pozitivní akci?',
      source: [
        { text: '.text-primary' },
        { text: '.text-info' },
        { text: '.text-success' },
        { text: '.text-warning' },
      ],
      ok: 2,
      link: 'https://www.tutorialspoint.com/Bootstrap-Contextual-classes',
    },
    {
      id: '23',
      text: 'Která kontextová třída naznačuje nebezpečnou nebo potenciálně negativní akci?',
      source: [
        { text: '.text-primary' },
        { text: '.text-info' },
        { text: '.text-warning' },
        { text: '.text-danger' },
      ],
      ok: 3,
      link: 'https://www.tutorialspoint.com/Bootstrap-Contextual-classes',
    },
    {
      id: '24',
      text: 'Která třída označuje text s velkými písmeny?',
      source: [
        { text: '.ucase' },
        { text: '.text-uppercase' },
        { text: '.text-capitalize' },
        { text: '.uppercase' },
      ],
      ok: 1,
      link: 'https://getbootstrap.com/docs/4.0/utilities/text/',
    },
    {
      id: '25',
      text: 'Bootstrap funguje na více zařízeních.',
      source: [
        { text: 'Ano' },
        { text: 'Ne' },
      
      ],
      ok: 0,
      link: 'https://getbootstrap.com/docs/5.0/layout/breakpoints/',
    },


  ],

  Sass: [
    {
      id: '1',
      text: '________ definuje pravidla stylů pro různé typy médií.',
      source: [
        { text: '@media' },
        { text: '@import' },
        { text: '@rozšířit' },
        { text: '@ladit' },
  
      ],
      ok: 0,
      link: 'https://sass-lang.com/documentation/at-rules/css#media',
    },
    {
      id: '2',
      text: 'Pomocí @debug najdeme chyby a zobrazíme hodnoty SassScriptu.',
      source: [
        { text: 'Ano' },
        { text: 'Ne' },
      
  
      ],
      ok: 0,
      link: 'https://sass-lang.com/documentation/at-rules/debug',
    },
    {
      id: '3',
      text: 'Pomocí které z možností můžeme sdílet css z jedonoho selektoru do druhého?',
      source: [
        { text: '@extend ' },
        { text: '@media' },
        { text: 'žádná z výše uvedených možností' },
      
  
      ],
      ok: 0,
      link: 'https://sass-lang.com/documentation/at-rules/extend',
    },
    {
      id: '4',
      text: 'Sadu vnořených pravidel, které mohou vytvořit blok stylů v kořenovém adresáři dokumentu vytvoříme pomocí:',
      source: [
        { text: '@at-root ' },
        { text: '@media' },
        { text: '@extend' },
        { text: 'žádná z výše uvedených možností' },
      
  
      ],
      ok: 0,
      link: 'https://sass-lang.com/documentation/at-rules/at-root',
    },
    {
      id: '5',
      text: 'Chceme-li zobrazot chybu, použijeme:',
      source: [
        { text: '@error' },
        { text: '@warn' },
        { text: '@at-root' },
        { text: 'žádnou z výše uvedených možností' },
      
  
      ],
      ok: 0,
      link: 'https://sass-lang.com/documentation/at-rules/error',
    },
    {
      id: '6',
      text: 'Jak v Sassu definujeme proměnnou?',
      source: [
        { text: '@primary-color: #888;' },
        { text: '%primary-color: #888;' },
        { text: '#primary-color: #888;' },
        { text: '$primary-color: #888;  ' },
      
  
      ],
      ok: 3,
      link: 'https://sass-lang.com/documentation/modules/color',
    },
    {
      id: '7',
      text: 'Hodnoty ze SassScriptu se v mixinech jako hodnoty používají',
      source: [
        { text: 'Ano' },
        { text: 'Ne' },
      
  
      ],
      ok: 0,
      link: 'ttps://sass-lang.com/documentation/at-rules/mixin',
    },
    {
      id: '8',
      text: 'Proč se v Sass používá @include?',
      source: [
        { text: 'Chceme-li definovat mixin' },
        { text: 'Chceme-li zahrnout mixin do dokumentu' },
        { text: 'Vše výše uvedené' },
        { text: 'Nic z výše uvedeného' },
      
  
      ],
      ok: 1,
      link: 'https://sass-lang.com/documentation/at-rules/mixin',
    },
    {
      id: '9',
      text: 'Kterým heslem definujeme mixin?',
      source: [
        { text: '@include' },
        { text: '@mixin ' },
        { text: '@extend' },
        { text: '@debug' },
      
  
      ],
      ok: 1,
      link: 'https://sass-lang.com/documentation/at-rules/mixin',
    },
    {
      id: '10',
      text: 'Proč se v Sassu používá @return ?',
      source: [
        { text: 'Chceme-li definovat mixin' },
        { text: 'Chceme-li zahrnout mixin do dokumentu ' },
        { text: 'Chceme-li zuavolat mnávratovou hodnotu funkce' },
        { text: 'Nic z výše uvedeného' },
      
  
      ],
      ok: 2,
      link: 'https://sass-lang.com/documentation/at-rules/function#return',
    },
    {
      id: '11',
      text: 'Následující příkaz spustí kód Sass v příkazovém řádku: sass input.scss output.css',
      source: [
        { text: 'Ano' },
        { text: 'Ne' },
       
      ],
      ok: 0,
      link: 'https://sass-lang.com/documentation/cli/dart-sass#one-to-one-mode',
    },
    {
      id: '12',
      text: 'Jaký je rozdím mezi Sass and SCSS?',
      source: [
        { text: 'Sass je CSS preprocesor s vylepšenou syntaxí a rozšířením CSS3.' },
        { text: 'Sass má dvě syntaxe.' },
        { text: 'První syntaxe je „SCSS“ a používá příponu .scss.' },
        { text: ' Druhá syntaxe je odsazená syntaxe nebo jen „Sass“ a používá příponu .sass.' },
        { text: 'Vše výše uvedené ' },
      
  
      ],
      ok: 4,
      link: 'https://www.geeksforgeeks.org/what-is-the-difference-between-css-and-scss/',
    },
    {
      id: '13',
      text: '@IMPORT se v Sassu používá protože:',
      source: [
        { text: 'rozšiřuje pravidlo importu CSS a umožňuje importovat soubory SCSS a Sass' },
        { text: 'všechny importované soubory jsou sloučeny do jednoho výstupního souboru CSS' },
        { text: 'může spojovat soubory a jejich styly' },
        { text: 'přijímá název souboru k importu' },
        { text: 'Vše výše uvedené ' },
      
  
      ],
      ok: 4,
      link: 'https://sass-lang.com/documentation/at-rules/import',
    },
    {
      id: '14',
      text: 'Které datové typy SassScript podporuje?',
      source: [
        { text: 'Čísla( eg; 1,5 ,10px)' },
        { text: 'Textové řetězce ( g., "foo", "bar", etc.)' },
        { text: 'Barvy(blue, #04a3f9)' },
        { text: 'Pravdivostní hodnoty (true or false)' },
        { text: 'Pravdivostní hodnoty (true or false) ' },
      
  
      ],
      ok: 4,
      link: 'https://sass-lang.com/documentation/syntax/structure#literals',
    },
    {
      id: '15',
      text: 'Příkaz sass --watch input.scss:output.css slouží k:',
      source: [
        { text: 'ke sledování a aktualizaci CSS pokud v Sass souboru dojde ke změně  ' },
        { text: 'ke sledování celé adresáře, pokud Sass obsahuje mnoho souborů.' },
      
  
      ],
      ok: 0,
      link: 'https://sass-lang.com/documentation/cli/dart-sass',
    },
    {
      id: '16',
      text: 'K urychlení kompilace používáme:',
      source: [
        { text: ':cache ' },
        { text: ':read_cache' },
        { text: ':cache_store' },
      
  
      ],
      ok: 0,
      link: 'https://rstudio.github.io/sass/reference/sass.html#caching',
    },

  ],
};
